
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgtqoyqrurczabmtyvgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRndHFveXFydXJjemFibXR5dmdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNzU2MDQsImV4cCI6MjA2MDk1MTYwNH0.CjrweO3idGGtx6pSKE-ViijifSF1Pk6vHDV7OURGyjU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});

// Enable RLS policies on all channels
export const enableRealtimeTables = async () => {
  await supabase.channel('schema-db-changes')
    .on(
      'postgres_changes',
      {
        event: '*',
        schema: 'public',
      },
      (payload) => console.log('Real-time change:', payload)
    )
    .subscribe();
};
